name: autoretroab
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.10
  - numpy<2
  - pandas
  - pyyaml
  - snakemake
  - bowtie2
  - samtools
  - sra-tools
  - wget
  - r-base
  - bioconductor-deseq2
  - telescope
  - pip
